echo "
[[CURRENCIES]]
code = \"LATAMCOIN\"
issuer = \"GDH.......................................................................\" 
name = \"LatamCoin\"
desc = \"Moneda de prueba de la red Pi Testnet enfocada en la comunidad latinoamericana.\"
image = \"https://i.imgur.com/5MXJ616.png"
